version: "2"
services:
  app:
    build: app
    ports:
      - "80"
    volumes:
      - /tmp
  nginx:
    image: nginx
    links:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
